name: build and test
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  name: checkout respository
       uses: actions/checkout@v2
    -  name:  setup node.js
       uses: actions/setup-node@v2
       with: 
         node-version: '16.14'
    - name: setup yarn
      run: npm install -g yarn
    - name: install depencies
      run: yarn
    - name: build
      run: yarn build
    - name: copy files to server
      uses: appleboy/scp-action@master
      with: 
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME}}
        password: ${{secrets.PASSWORD}}
        port: 22
        source: "build/"
        target: "/usr/share/nginx"
      
